import Link from "next/link";import { ArrowRight, Sparkle, Scissors, MapPin, Heart, Leaf, UsersThree, InstagramLogo } from "@phosphor-icons/react/dist/ssr";import Hero from "@/components/Hero";import CategoryCard from "@/components/CategoryCard";import ProductCard from "@/components/ProductCard";import FAQ from "@/components/FAQ";import SeoTextBlock from "@/components/SeoTextBlock";import LocalBusinessBlock from "@/components/LocalBusinessBlock";import BlogCard from "@/components/BlogCard";import { categories } from "@/data/categories";import { products } from "@/data/products";import { blogPosts } from "@/data/blogPosts";import { faq } from "@/data/faq";import { JsonLd } from "@/components/JsonLd";import { faqSchema } from "@/lib/schema";
import ManagedFAQ from "@/components/ManagedFAQ";
import ManagedReviews from "@/components/ManagedReviews";
const reasons=[{icon:Sparkle,title:"Unikalne modele",text:"Krótkie serie i detale, których nie spotkasz wszędzie."},{icon:Scissors,title:"Szycie na zamówienie",text:"Fason, wymiar i wykończenie dopasowane do dziecka."},{icon:MapPin,title:"Lokalny butik",text:"Przymiarki i osobista pomoc w Dąbrowie Tarnowskiej."},{icon:Heart,title:"Indywidualne podejście",text:"Słuchamy dziecka i rodzica — bez pośpiechu i presji."},{icon:Leaf,title:"Dobre materiały",text:"Wybieramy przyjemne tkaniny, które dobrze się noszą."},{icon:UsersThree,title:"Dla dzieci i nastolatków",text:"Eleganckie fasony w wieku od kilku do kilkunastu lat."}];
export default function Home(){return <><JsonLd data={faqSchema(faq)}/><Hero/>
<section className="py-20 md:py-28 overflow-hidden"><div className="container-site"><div className="flex items-end justify-between gap-8 mb-10"><div><p className="eyebrow">Na każdą ważną chwilę</p><h2 className="section-title mt-5">Wybierz swoją opowieść</h2></div><Link href="/kolekcje" className="btn-text hidden md:flex">Wszystkie kolekcje <ArrowRight size={14}/></Link></div><div className="grid grid-cols-2 lg:grid-cols-3 gap-3 md:gap-5">{categories.map((c,i)=><CategoryCard key={c.slug} category={c} large={i<2}/>)}</div></div></section>
<section className="soft py-20 md:py-28"><div className="container-site"><div className="grid lg:grid-cols-[.65fr_1.35fr] gap-12 lg:gap-20"><div><p className="eyebrow">Dlaczego my</p><h2 className="section-title mt-5">Mały butik.<br/><em>Wielka uważność.</em></h2><p className="text-[#756b64] leading-relaxed mt-6 max-w-md">Nie chcemy ubierać wszystkich tak samo. Szukamy proporcji, koloru i detalu, które pasują właśnie do Was.</p></div><div className="grid sm:grid-cols-2 gap-x-10">{reasons.map(({icon:Icon,title,text},i)=><div key={title} className="py-6 border-b hairline grid grid-cols-[auto_1fr] gap-4"><span className="text-[#947653] pt-1"><Icon size={22} weight="thin"/></span><div><p className="serif text-xl">{title}</p><p className="text-sm text-[#756b64] mt-2 leading-relaxed">{text}</p></div></div>)}</div></div></div></section>
<section className="py-20 md:py-28"><div className="container-site"><div className="flex items-end justify-between gap-8 mb-10"><div><p className="eyebrow">Wybrane dla Was</p><h2 className="section-title mt-5">Najczęściej oglądane</h2></div><Link href="/kolekcje" className="btn-text hidden md:flex">Przejdź do katalogu <ArrowRight size={14}/></Link></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-x-5 gap-y-12">{products.filter(p=>p.featured).slice(0,4).map(p=><ProductCard key={p.slug} product={p}/>)}</div></div></section>
<section className="grid lg:grid-cols-2 min-h-[650px] bg-[#29211d] text-[#f8f5ef]"><div className="relative min-h-[480px] overflow-hidden grain"><img src="/images/sukienka-aurora.png" alt="Sukienka szyta na zamówienie w pracowni Little Ceremony" className="absolute inset-0 w-full h-full object-cover"/></div><div className="p-8 md:p-16 lg:p-20 flex flex-col justify-center"><p className="eyebrow !text-[#c7a777] before:!bg-[#c7a777]">Szycie na zamówienie</p><h2 className="section-title mt-5">Twój pomysł.<br/><em>Nasz wspólny projekt.</em></h2><p className="text-white/65 leading-relaxed mt-6 max-w-lg">Czasem wymarzony strój nie czeka na wieszaku. Możemy stworzyć go od początku — od pierwszego szkicu i wyboru materiału po ostatnią przymiarkę.</p><ol className="grid grid-cols-2 gap-4 mt-8 text-sm text-white/70">{["Rozmowa i inspiracje","Dobór materiałów","Pomiar i przymiarka","Szycie i odbiór"].map((x,i)=><li key={x} className="border-t border-white/20 pt-3"><span className="text-[#c7a777] mr-2">0{i+1}</span>{x}</li>)}</ol><Link href="/szycie-na-zamowienie" className="btn border-white text-white w-fit mt-9 hover:bg-white hover:text-[#29211d]">Opisz swój pomysł <ArrowRight size={16}/></Link></div></section>
<SeoTextBlock/><LocalBusinessBlock/>
<section className="py-20 md:py-28"><div className="container-site"><div className="grid lg:grid-cols-[.7fr_1.3fr] gap-12"><div><p className="eyebrow">Dobre słowa</p><h2 className="section-title mt-5">Wasze małe<br/>wielkie momenty</h2><p className="text-xs text-[#9b8f85] mt-5">Opinie rodzin, które odwiedziły nasz butik.</p></div><ManagedReviews/></div></div></section>
<section className="soft py-20 md:py-28"><div className="container-site"><div className="flex items-end justify-between gap-8 mb-10"><div><p className="eyebrow">Poradnik</p><h2 className="section-title mt-5">Spokojne wybory zaczynają się tutaj</h2></div><Link href="/poradnik" className="btn-text hidden md:flex">Wszystkie artykuły <ArrowRight size={14}/></Link></div><div className="grid md:grid-cols-3 gap-8">{blogPosts.slice(0,3).map(p=><BlogCard key={p.slug} post={p}/>)}</div></div></section>
<section className="py-20 md:py-28"><div className="container-site grid lg:grid-cols-[.7fr_1.3fr] gap-12"><div><p className="eyebrow">Pytania i odpowiedzi</p><h2 className="section-title mt-5">Zanim się spotkamy</h2></div><ManagedFAQ/></div></section>
<section className="bg-[#ead8d1] py-16"><div className="container-site flex flex-col md:flex-row items-center justify-between gap-8"><div><p className="eyebrow">Bądź blisko</p><h2 className="serif text-3xl md:text-4xl mt-3">Nowe kolekcje, małe serie, inspiracje.</h2></div><form className="flex w-full md:max-w-md"><label className="sr-only" htmlFor="newsletter">Adres e-mail</label><input id="newsletter" type="email" required placeholder="Twój adres e-mail" className="field bg-transparent border-[#29211d]"/><button className="w-14 shrink-0 bg-[#29211d] text-white flex items-center justify-center" aria-label="Zapisz się"><ArrowRight size={18}/></button></form></div></section>
</>}
