"use client";
import { useState, type FormEvent } from "react";
import { ArrowRight, Check } from "@phosphor-icons/react";
export default function ContactForm({type="contact",product}:{type?:"contact"|"product"|"custom";product?:string}){
 const [sent,setSent]=useState(false); const [loading,setLoading]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);await fetch("/api/zapytanie",{method:"POST",body:new FormData(e.currentTarget)});setLoading(false);setSent(true)}
 if(sent)return <div className="paper border hairline min-h-[320px] p-10 flex flex-col items-center justify-center text-center"><span className="w-14 h-14 rounded-full bg-[#e2eadf] text-[#395f50] flex items-center justify-center"><Check size={25}/></span><h3 className="serif text-3xl mt-5">Dziękujemy za wiadomość</h3><p className="text-[#756b64] max-w-md mt-3">To wersja demonstracyjna formularza. Po podłączeniu usługi e-mail zapytanie trafi bezpośrednio do butiku.</p><button onClick={()=>setSent(false)} className="btn-text mt-6">Wyślij kolejną wiadomość</button></div>;
 return <form onSubmit={submit} className="grid md:grid-cols-2 gap-5" encType="multipart/form-data">
  <input type="hidden" name="formType" value={type}/>{product&&<input type="hidden" name="product" value={product}/>}<div><label className="label">Imię i nazwisko *</label><input required name="name" className="field" placeholder="Anna Kowalska"/></div><div><label className="label">Telefon *</label><input required name="phone" inputMode="tel" className="field" placeholder="+48 000 000 000"/></div><div><label className="label">E-mail *</label><input required name="email" type="email" className="field" placeholder="anna@email.pl"/></div>
  {type==="contact"&&<div><label className="label">Temat</label><select name="subject" className="field"><option>Zapytanie ogólne</option><option>Przymiarka</option><option>Dostępność produktu</option></select></div>}
  {type!=="contact"&&<><div><label className="label">Wiek dziecka</label><input name="age" className="field" placeholder="np. 10 lat"/></div><div><label className="label">Rozmiar</label><input name="size" className="field" placeholder="np. 140"/></div><div><label className="label">Data wydarzenia</label><input name="eventDate" type="date" className="field"/></div></>}
  {type==="custom"&&<><div><label className="label">Rodzaj ubrania</label><select name="garment" className="field"><option>Sukienka</option><option>Garnitur</option><option>Komplet</option><option>Inne</option></select></div><div className="md:col-span-2"><label className="label">Zdjęcie inspiracji</label><input name="inspiration" type="file" accept="image/*" className="field file:mr-3 file:border-0 file:bg-[#eee6da] file:px-3 file:py-1"/></div></>}
  <div className="md:col-span-2"><label className="label">{type==="custom"?"Opisz swój pomysł":"Wiadomość"}</label><textarea required name="message" rows={5} className="field resize-y" placeholder="Napisz, czego szukasz i jak możemy pomóc…"/></div><label className="md:col-span-2 flex gap-3 text-xs text-[#756b64] leading-relaxed"><input required type="checkbox" name="rodo" className="mt-1 accent-[#29211d]"/> Wyrażam zgodę na przetwarzanie danych w celu obsługi mojego zapytania. Zapoznałam/em się z polityką prywatności.</label><div className="md:col-span-2"><button disabled={loading} className="btn btn-dark w-full md:w-auto">{loading?"Wysyłanie…":"Wyślij zapytanie"}<ArrowRight size={16}/></button></div>
 </form>
}
