import { siteConfig } from "@/data/siteConfig";
import type { Product } from "@/data/products";
import type { BlogPost } from "@/data/blogPosts";
export const organizationSchema = { "@context": "https://schema.org", "@type": "Organization", name: siteConfig.name, url: siteConfig.url, email: siteConfig.email, telephone: siteConfig.phone };
export const localBusinessSchema = { "@context": "https://schema.org", "@type": "ClothingStore", name: siteConfig.name, url: `${siteConfig.url}/sklep-dabrowa-tarnowska`, telephone: siteConfig.phone, priceRange: "$$", address: { "@type": "PostalAddress", streetAddress: siteConfig.address.street, postalCode: siteConfig.address.postalCode, addressLocality: siteConfig.address.city, addressRegion: siteConfig.address.region, addressCountry: siteConfig.address.country } };
export const faqSchema = (items: { question: string; answer: string }[]) => ({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: items.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) });
export const productSchema = (product: Product) => ({ "@context": "https://schema.org", "@type": "Product", name: product.name, image: `${siteConfig.url}${product.image}`, description: product.description, sku: product.slug, brand: { "@type": "Brand", name: siteConfig.name }, offers: { "@type": "Offer", url: `${siteConfig.url}/produkty/${product.slug}`, priceCurrency: "PLN", availability: product.availability === "Dostępny" ? "https://schema.org/InStock" : "https://schema.org/PreOrder" } });
export const breadcrumbSchema = (items: { name: string; url: string }[]) => ({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: items.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.name, item: `${siteConfig.url}${item.url}` })) });
export const blogPostingSchema = (post: BlogPost) => ({ "@context": "https://schema.org", "@type": "BlogPosting", headline: post.title, description: post.excerpt, image: `${siteConfig.url}${post.image}`, author: { "@type": "Organization", name: siteConfig.name }, publisher: { "@type": "Organization", name: siteConfig.name }, datePublished: "2026-03-12" });
