"use client";
import { useState } from "react";
import { EnvelopeSimple,Plus,Trash } from "@phosphor-icons/react";
import type { Promotion,Review } from "@/lib/admin-store";

export default function AdminMarketing({initialReviews,initialPromotions}:{initialReviews:Review[];initialPromotions:Promotion[]}){
  const [reviews,setReviews]=useState(initialReviews);
  const [promotions,setPromotions]=useState(initialPromotions);
  async function addReview(){const item={name:"Nowa klientka",city:"Dąbrowa Tarnowska",email:"",text:"Wpisz treść opinii…",rating:5,event:"Komunia",visible:false,status:"Nowa",createdAt:new Date().toISOString()};const r=await fetch("/api/admin/content",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({collection:"reviews",item})});setReviews([await r.json(),...reviews])}
  async function addPromotion(){const item={name:"Nowa promocja",description:"Opis promocji",code:"",active:false};const r=await fetch("/api/admin/content",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({collection:"promotions",item})});setPromotions([await r.json(),...promotions])}
  async function save(collection:"reviews"|"promotions",item:Review|Promotion){const payload=collection==="reviews"?{...item,repliedAt:(item as Review).adminReply?new Date().toISOString():(item as Review).repliedAt}:item;const r=await fetch("/api/admin/content",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({collection,item:payload})});const result=await r.json();collection==="reviews"?setReviews(reviews.map(x=>x.id===result.id?result:x)):setPromotions(promotions.map(x=>x.id===result.id?result:x))}
  async function remove(collection:"reviews"|"promotions",id:string){await fetch(`/api/admin/content?collection=${collection}&id=${id}`,{method:"DELETE"});collection==="reviews"?setReviews(reviews.filter(x=>x.id!==id)):setPromotions(promotions.filter(x=>x.id!==id))}
  return <div className="grid xl:grid-cols-2 gap-6"><section><div className="flex justify-between items-center"><div><h2 className="font-semibold">Opinie klientów</h2><p className="text-xs text-[#7d858d] mt-1">Nowe opinie wymagają moderacji.</p></div><button onClick={addReview} className="admin-btn admin-btn-primary"><Plus/> Dodaj</button></div><div className="space-y-3 mt-4">{reviews.map(x=><ReviewRow key={x.id} item={x} save={save} remove={remove}/>)}</div>{!reviews.length&&<div className="admin-card p-8 text-center text-sm text-[#7d858d] mt-4">Brak nowych opinii.</div>}</section><section><div className="flex justify-between items-center"><h2 className="font-semibold">Promocje i kupony</h2><button onClick={addPromotion} className="admin-btn admin-btn-primary"><Plus/> Dodaj</button></div><div className="space-y-3 mt-4">{promotions.map(x=><PromoRow key={x.id} item={x} save={save} remove={remove}/>)}</div></section></div>
}

function ReviewRow({item,save,remove}:{item:Review;save:(c:"reviews",x:Review)=>void;remove:(c:"reviews",id:string)=>void}){
  const [draft,setDraft]=useState(item);
  const status=draft.status||(draft.visible?"Opublikowana":"Ukryta");
  return <div className="admin-card p-4 grid gap-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><span className={`text-[10px] uppercase tracking-wide px-2 py-1 rounded-full ${status==="Nowa"?"bg-amber-50 text-amber-700":status==="Opublikowana"?"bg-green-50 text-green-700":"bg-[#f1f2f3] text-[#69717b]"}`}>{status}</span>{draft.createdAt&&<p className="text-[11px] text-[#858c94] mt-2">{new Date(draft.createdAt).toLocaleString("pl-PL")}</p>}</div><div className="text-[#b4986d]">{"★".repeat(draft.rating)}</div></div>
    <div className="grid grid-cols-2 gap-3"><div><label className="admin-label">Imię</label><input className="admin-input" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></div><div><label className="admin-label">Miasto</label><input className="admin-input" value={draft.city} onChange={e=>setDraft({...draft,city:e.target.value})}/></div></div>
    {draft.email&&<div><label className="admin-label">Prywatny e-mail</label><a href={`mailto:${draft.email}?subject=Odpowiedź%20Little%20Ceremony`} className="admin-btn admin-btn-secondary w-fit"><EnvelopeSimple/>{draft.email}</a></div>}
    <div><label className="admin-label">Opinia klienta</label><textarea className="admin-input" rows={4} value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/></div>
    <div><label className="admin-label">Odpowiedź butiku</label><textarea className="admin-input" rows={4} value={draft.adminReply||""} onChange={e=>setDraft({...draft,adminReply:e.target.value})} placeholder="Napisz odpowiedź, która pojawi się pod opinią…"/></div>
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><label className="text-sm flex items-center gap-2"><input type="checkbox" checked={draft.visible} onChange={e=>setDraft({...draft,visible:e.target.checked,status:e.target.checked?"Opublikowana":"Ukryta"})}/> Opublikowana na stronie</label><div className="flex gap-2"><button onClick={()=>remove("reviews",draft.id)} className="admin-btn admin-btn-secondary text-red-600"><Trash/> Usuń</button><button onClick={()=>save("reviews",draft)} className="admin-btn admin-btn-primary">Zapisz i odpowiedz</button></div></div>
  </div>
}

function PromoRow({item,save,remove}:{item:Promotion;save:(c:"promotions",x:Promotion)=>void;remove:(c:"promotions",id:string)=>void}){const [draft,setDraft]=useState(item);return <div className="admin-card p-4 grid gap-3"><input className="admin-input" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><textarea className="admin-input" rows={2} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/><input className="admin-input" placeholder="Kod rabatowy" value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value})}/><div className="flex justify-between"><label className="text-sm flex gap-2"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> Aktywna</label><div className="flex gap-2"><button onClick={()=>remove("promotions",draft.id)} className="admin-btn admin-btn-secondary text-red-600"><Trash/></button><button onClick={()=>save("promotions",draft)} className="admin-btn admin-btn-primary">Zapisz</button></div></div></div>}
